name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the head commit of the branch
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Rust install
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.58.1
        override: true
        components: clippy, rustfmt
    - name: Check rust format
      run: cargo fmt --all -- --check
    - name: Check clippy
      run: cargo clippy --all
    - name: Check clippy for tests
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Build
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Style Check
      run: cargo clippy -- -D warnings
    - name: Run doc
      run: export RUSTDOCFLAGS="-Dwarnings" && cargo doc --no-deps
